---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: boiler
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: jpcordeiro/boiler-api:latest
          imagePullPolicy: Always
          env:
            - name: TPLINK_USER
              value: "tplinkusermail"
            - name: TPLINK_PASS
              value: "tplinkpass"
            - name: TPLINK_DEVICE
              value: "Chaudiere"
            - name: DBHOST
              value: mysql-service
            - name: DBUSER
              value: root
            - name: DBPORT
              value: "3306"
            - name: DATABASE
              value: "Boiler"
            - name: TABLE
              value: "Boiler"
---
#
# Service
#
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: boiler
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: api
---
#
# Ingress
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: boiler
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: api.boiler.lean-sys.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 3000
  tls:
    - secretName: api-tls
      hosts:
        - api.boiler.lean-sys.com
