---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: get
  namespace: boiler
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: get
            image: jpcordeiro/boiler-get:latest
            imagePullPolicy: Always
            env:
              - name: TPLINK_USER
                value: "tplinkusermail"
              - name: TPLINK_PASS
                value: "xxxxxx"
              - name: TPLINK_DEVICE
                value: "xxxxxx"
              - name: DBHOST
                value: mysql-service
              - name: DBUSER
                value: root
              - name: DBPORT
                value: "3306"
              - name: DATABASE
                value: "Boiler"
              - name: TABLE
                value: "Boiler"
          restartPolicy: OnFailure

