---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: get
  namespace: boiler
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: get
            image: jpcordeiro/boiler-get:latest
            imagePullPolicy: Always
            env:
              - name: TPLINK_USER
                value: "xxxxx"
              - name: TPLINK_PASS
                value: "xxxxx"
              - name: TPLINK_DEVICE
                value: "xxxxx"
              - name: DBHOST
                value: mongo-service
              - name: DBPORT
                value: "27017"
              - name: DATABASE
                value: "Boiler"
              - name: TABLE
                value: "power"
          restartPolicy: OnFailure

