#FROM node:lts-bullseye-slim
FROM alpine
RUN apk add --update npm
ENV TZ Europe/Paris
WORKDIR /usr/src/app
RUN npm install tplink-cloud-api
RUN npm install uuid
RUN npm install mongoose
RUN npm audit fix --force
COPY GetConsoMongoDB.js .
CMD [ "node", "GetConsoMongoDB.js" ]
