#FROM node:lts-bullseye-slim
FROM alpine
RUN apk add --update npm
ENV TZ Europe/Paris
WORKDIR /usr/src/app
RUN npm install tplink-cloud-api
RUN npm install uuid
RUN npm install mysql
RUN npm audit fix --force
COPY GetConsoMySQL.js .
CMD [ "node", "GetConsoMySQL.js" ]
