FROM node:buster
ENV TZ Europe/Paris

#Install Cron
RUN apt-get update
RUN apt-get -y install cron
# Add crontab file in the cron directory
ADD crontabCalc /etc/cron.d/crontabCalc
# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/crontabCalc
# Create the log file to be able to run tail
RUN touch /var/log/cron.log

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install
COPY CalcConsoMySQL.js .

COPY SetCronEnvs.sh .
COPY cronCalc.sh .
RUN chmod +x /usr/src/app/*.sh

CMD /usr/src/app/SetCronEnvs.sh && cron && tail -f /var/log/cron.log
