---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume
  namespace: boiler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo
  name: mongo
  namespace: boiler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        args: ["--dbpath","/data/db"]
        volumeMounts:
        - name: "mongo-data-dir"
          mountPath: "/data/db"
      volumes:
      - name: "mongo-data-dir"
        persistentVolumeClaim:
          claimName: "mongo-volume"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: boiler
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    app: mongo